### PR TITLE
Fixed issue when adding the Thymeleaf nature

### LINKED ISSUE #40: Add Thymeleaf Nature only works for Java Projects
I couldn't get the content assist to work, but fortunately I found issue #25 where you explain how to debug eclipse plugins. Doing this I found out that when I execute "Add Thymeleaf Nature" on my web project I get this Exception:

Caused by: java.lang.ClassCastException: org.eclipse.core.internal.resources.Project cannot be cast to org.eclipse.jdt.core.IJavaProject at org.thymeleaf.extras.eclipse.nature.AddThymeleafNatureAction.execute(AddThymeleafNatureAction.java:47)
etc.

So I changed my project to a plain Java project and voilá: it works. This is unfortunate since I guess everybody developing Thymeleaf templates is doing so in some kind of web project. Apart from that: thanx for developing the plugin.

Workaround: add java nature to <natures> in .project:
<nature>org.eclipse.jdt.core.javanature</nature>

### LINKED ISSUE #42: Can't Add Thymeleaf Nature to Project
I Installed the plugin through the update-site and I'm running the latest Kepler.

When I try to Add Thymeleaf Nature to my project I get an Error : Unhandled event loop exception.

I've also tried adding Thymeleaf Nature to a clean new Dynamic Web Project.

Exception Stack Trace:

```
org.eclipse.e4.core.di.InjectionException: java.lang.ClassCastException: org.eclipse.core.internal.resources.Project cannot be cast to org.eclipse.jdt.core.IJavaProject
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:63)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:243)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:224)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:167)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:850)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:743)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:727)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:662)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
Caused by: java.lang.ClassCastException: org.eclipse.core.internal.resources.Project cannot be cast to org.eclipse.jdt.core.IJavaProject
    at org.thymeleaf.extras.eclipse.nature.AddThymeleafNatureAction.execute(AddThymeleafNatureAction.java:47)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    ... 37 more
```

### PR DESCRIPTION
**Pull request by tduchateau**
The projects are now buffered in a List of IProject before the nature is to be applied
Fixes #40 and fixes #42

### CODE REVIEW

**Comment by ultraq** [comment]
Still can't believe that it comes as an `IJavaProject` for some (ie: all my Eclipse installs), but an `IProject` for others - crazy Eclipse!  Anyway, thanks again for squashing this bug.

Neil Patrick Harris thumbs up

**Comment by tduchateau** [comment]
Haha!
You're welcome. I must confess that it remains a mistery to me too :-/

**Comment by tduchateau** [comment]
By the way, any idea for the release date?

**Comment by ultraq** [comment]
With this major bug out of the way, I'm now thinking of just deferring my current work on fragment suggestions (#31, #32) to a later release (it's taking a lot longer than I hoped), and working on the ones that actually support new Thymeleaf 2.1 features (#34, #37) to get them and this bug fix out the door.  If I follow that plan, then I hope to have things done by next weekend.

**Comment by tduchateau** [comment]
OK thanks!

**Pull request merged**
